### ISSUE TITLE
Implement FetchLock.

### ISSUE THREAD

**Issue by Object905** [slide-rs/shred#32]
You may have a system that work mostly on read resources, but sometimes needs writing some resource, for example to execute callback, that may need to write this some resource, or computes mostly with read resources and then stores result into some write resource. Without locking fetch this will be inefficient, since execution of this system will be delayed, because of this write resource.

### Implementation
I think that it has to be implemented with `std::sync::RwLock`, since `Resource` trait is `Send + Sync` anyway.
Also i think that `FetchLock` resource will be counted as "read resource" internally, but It will be nice if we mark it somehow, to sort system dependencies to make locking on the same resource less probable, because when I roll out PR on #6, this will be possible.

**Comment by kvark** [comment]
While in general `FetchLock` seems to have a use case, I'd be cautious adding it because we can't guarantee the absence of deadlocks in this case. Perhaps, it should be left out of scope, since the user is free to share some `Arc<RwLock<T>>` wherever they please, and we aren't responsible for associated deadlocks.

**Comment by torkleyy** [comment]
I agree with @kvark. Closing for now.

**Comment by torkleyy** [comment]
Just as a side note, if you find your system only writing to some resource for a short period, try to split it up into multiple systems.
