### ISSUE TITLE
Benchmark and improve dispatching

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/shred#6]
The current implementation of fetching the next task to execute is very naive (the implementation is about [here](https://github.com/torkleyy/shred/blob/c145e9e86bb0656a7cc66cbaf1f6b092d9eb8e5f/src/dispatch.rs#L80)).

It may be an advantage that, because of the builder, useful information could be pre-computed, although I'm clueless how and what exactly.

**Comment by msiglreith** [comment]
Another aspect to look into would be to bench the difference between the current busy-waiting approach for finding a new system to dispatch and a signal based approach which emits signals after each call.

(A more advanced hybrid method could be of interest in the future, depending on the results..)

**Comment by torkleyy** [comment]
@msiglreith Good idea! I do not consider this a very high priority, but once we got all the functionality, I'll investigate this.

**Comment by Object905** [comment]
Working on it. Expect big PR soon. My method is to compute dependencies of systems and then make use of combining `pulse`s `Select` and `Barrier` to dispatch systems.

**Comment by torkleyy** [comment]
@Object905 Me too! I have a completely different approach, let's see which one performs better.

**Comment by Object905** [comment]
@torkleyy actually your approach is almost just like mine, but in my approach i make use of barriers and scopes, while in your PR there is parallel iterators. In rayon docs [in scope](https://docs.rs/rayon/0.7.1/rayon/fn.scope.html) function there is a note that parallel iterators and `join`s will be better, because scope() must be allocated onto the heap, so i think that your approach will be better.
