### ISSUE TITLE
Check if the `Resources` are empty

### ISSUE THREAD

**Issue by torkleyy** [slide-rs/shred#87]
If a resource couldn't be fetched and `Resources` is empty, it might be because somebody accidentally created a new instance by specifying it as `SystemData`. This should be pointed out in the panic.

**Comment by torkleyy** [comment]
cc @Moxinilian

**Comment by DefecateRainbows** [comment]
Would it also be reasonable to add some way to iterate over the types of resources stored? I recently found that I needed this, and somebody else on the specs github issues found that they needed this as well.
Since it's stored in a hash map, that could actually be as simple as making the resources field public, although I'd prefer some other sort of API.

**Comment by DefecateRainbows** [comment]
I could also do #111 while I'm over there.

**Comment by torkleyy** [comment]
> Would it also be reasonable to add some way to iterate over the types of resources stored?

Yes, I think that would be useful, too. I think the simplest solution would be to just create a method that returns an iterator over the values, yielding `&Resource`. The keys aren't really interesting since they're just the type ids.

**Comment by torkleyy** [comment]
@DefecateRainbows are you still interested in this?
