### ISSUE TITLE
Cannot create dynamic `ResourceId`s

### ISSUE THREAD

**Issue by Diggsey** [slide-rs/shred#94]
The [documentation](https://docs.rs/shred/0.7.0/shred/struct.ResourceId.html) states that a `ResourceId` is:
>The id of a Resource, which is a tuple struct with a type id and an additional resource id (represented with a usize).

However, it only contains a `TypeId`, which means there's no way to dynamically construct a `ResourceId`!

**Comment by torkleyy** [comment]
That documentation is outdated. There's no way to fetch a resource by resource id, that's why it got removed. If you need a dynamic type map, I recommend storing inside a statically typed resource.

**Comment by Diggsey** [comment]
I am interested in the ability for scripts to define their own component types for use with specs, but specs controls access to resources using the `shred::Accessor` trait, and that trait uses the `ResourceId` to identify a resource. If a scripts defined two components types, `A` and `B`, there would be no way for the script to implement a system that updated `A` based on `B`, because there would be no way to distinguish the two (all script-defined component types would have to have the same static type, or at least be one of a set of predefined types).

**Comment by torkleyy** [comment]
Yeah, for scripting here some notes / recommendations:

* differentiate between Rust-defined components and script components
* register components in a map mapping strings to an enum
  * that enum is either a `ResourceId` or an id for a script component
* script components live in an extra resource
* make sure to register that container of the component storages as `AnyStorage` in order to delete components when the entities get deleted
* the accessor is mostly is used so that you don't need to specify the system data at compile time, you can see how that's done (and also some concepts how scripting needs to be implemented) in this example: https://github.com/slide-rs/shred/blob/master/examples/dyn_sys_data.rs

Those were some random notes, feel free to ask more questions!

**Comment by Diggsey** [comment]
@torkleyy that example is useful, and it's pretty much what I had in mind. The problem is that I wanted to define *resources themselves* from scripts. As long as `ResourceId`s are defined at compile-time, there's not really a way to do that... Well I suppose I could use a macro and define like 100 of them at compile time, and then allocate them at runtime and hope I don't run out... 🤢

**Comment by OvermindDL1** [comment]
In my old engine component tables were registered in the world context via an atom64 name (think a 64-bit unique integer that referenced as a string in code like `"something"_atom64`), and scripts could register their own tables that way as well.  Getting static access to a table means you could call on it directly, but getting dynamic access to a component table (like accessing a script-defined component table, or access any table from a script) went through the reflection interface on the component tables (a slight overhead but the function object lookups could be saved where-ever to allow for near-native access speeds once looked up, so a lookup could be done at load time for example).  They weren't even that slow to use from systems as a system can build an component aspect list from dynamic names as well (at run-time though instead of compiled up at build-time).
